Stock market Graph
cloudtrack/AWS-COVID-Analytics pull request #9
Opened 2021-11-28 15:12 UTC by muhwagwa

added stock market graph

2021-11-28 15:34 UTC, rachelg98 commented on aws-team-n/frontend/src/components/StockMarket/Continent/Africa.js
> +  });
dependency array가 없으면 랜더마다 dispatch 함수가 실행하게 되는데  추가해시는 게 좋을 것 같아요.

2021-11-28 16:26 UTC, juimdpp approved these changes
수고하셨습니다!
초반에 npm install 해야한는 것들이 조금 떴었는데, package.json에 추가하시면 좋을것 같아요!
그리고 디자인면에 있어서는 그래프 부분이 로딩되는 시간이 조금 걸리는데, 로딩되고 있다고 표시하는게 있으면 좋을것 같아요!
그리고 전반적으로 랙 현상이 조금 보이는데 이를 조금이라도 개선하면 좋을것 같아요!

2021-11-29 07:11 UTC, muhwagwa commented on aws-team-n/frontend/src/components/StockMarket/Continent/Africa.js
> +  });
아하 넵넵 추가할게요 감사합니다!

2021-11-29 18:27 UTC, muhwagwa commented
DONE
- store 삭제하고 flask로 서버 변경 + s3에서 데이터 가져오기

TO DO
- map graph 변경 (googlechart 말고 다른거 쓰기 + 데이터이동) + develop
- 섹터 그래프 작동 제대로 안 하는거 원인 파악

2021-12-01 17:09 UTC, rachelg98 approved these changes

2021-12-03 15:05 UTC, rachelg98 requested changes

2021-12-03 15:05 UTC, rachelg98 commented on aws-team-n/frontend/src/components/StockMarket/WorldRecover/Geo.js
> +import { getGeo } from '../../../store/StockMarketStore';
혹시 store폴더를 푸시안 하셨나요? pull하고 돌릴때 module not found에러가 뜨네요.

2021-12-03 19:49 UTC, muhwagwa commented on aws-team-n/frontend/src/components/StockMarket/WorldRecover/Geo.js
> +import { getGeo } from '../../../store/StockMarketStore';
아 제가 store 삭제하면서 약간 잔해(?)가 남았나봐요ㅠ 수정해서 다시 올릴게요!

2021-12-07 08:21 UTC, rachelg98 approved these changes

2021-12-08 18:54 UTC, merged